DROP TABLE Books;
CREATE TABLE Books (
	BookISBN VARCHAR2(10) PRIMARY KEY,
	BookTitle VARCHAR2(200),
	Genre VARCHAR2(150),
	QtyOnHand NUMBER
);

INSERT INTO Books VALUES (9780102846,'The Great Escape','Art Books',6);
INSERT INTO Books VALUES (9780102847,'Underbelly : The Gangland War','Art Books',4);
INSERT INTO Books VALUES (9780102848,'Oxford Guide to Plain English','Art Books',9);
INSERT INTO Books VALUES (9780102849,'Get Talking and Keep Talking Portuguese Total Audio Course ','Art Books',7);
INSERT INTO Books VALUES (9780102850,'The Truthful Art : Data, Charts, and Maps for Communication','Art Books',1);
INSERT INTO Books VALUES (9780102851,'Dreyer''s English : An Utterly Correct Guide to Clarity and Style','Art History',9);
INSERT INTO Books VALUES (9780102852,'In the Heart of the Sea : The Tragedy of the Whaleship Essex','Art History',4);
INSERT INTO Books VALUES (9780102853,'Halo: The Great Journey : The Art of Building Worlds','Art History',3);
INSERT INTO Books VALUES (9780102854,'Between You and Me : Confessions of a Comma Queen','Art History',3);
INSERT INTO Books VALUES (9780102855,'Alive : The Story of the Andes Survivors','Oriental Art',3);
INSERT INTO Books VALUES (9780102856,'The Adobe Photoshop Lightroom Classic CC Book for Digital Photographers','Art History: Renaissance',1);
INSERT INTO Books VALUES (9780102857,'Japanese Stories for Language Learners : Bilingual Stories in Japanese and English ','Styles: Art and Craft',2);
INSERT INTO Books VALUES (9780102858,'Ireland - Culture Smart! : The Essential Guide to Customs and Culture','Art History: From c 1960',7);
INSERT INTO Books VALUES (9780102859,'The Art of Incredibles 2','Art History: From c 1960',4);
INSERT INTO Books VALUES (9780102860,'Daily Word Ladders','Art History: From c 1960',2);
INSERT INTO Books VALUES (9780102861,'Lands of Lost Borders Lib/E : A Journey on the Silk Road','Styles: Conceptual Art',9);
INSERT INTO Books VALUES (9780102862,'Build Your Own CNC Machine','Styles: Conceptual Art',0);
INSERT INTO Books VALUES (9780102863,'Spelling Ages 5-6: New Edition','Precious Metal and Precious Stones: Artworks and Design',4);
INSERT INTO Books VALUES (9780102864,'Infused : Adventures in Tea','Electronic and Video Art',2);
INSERT INTO Books VALUES (9780102865,'The Art of Tom Clancy''s The Division','Electronic and Video Art',8);
INSERT INTO Books VALUES (9780102866,'Practice Makes Perfect German Vocabulary','Electronic and Video Art',9);
INSERT INTO Books VALUES (9780102867,'The First Third and Other Writings','Electronic and Video Art',4);
INSERT INTO Books VALUES (9780102868,'Discussing Design','Electronic and Video Art',7);
INSERT INTO Books VALUES (9780102869,'Allen and Greenough''s New Latin Grammar','Pottery and Glassware',6);
INSERT INTO Books VALUES (9780102870,'The Twice-Born : Life and Death on the Ganges','Decorative Arts',9);
INSERT INTO Books VALUES (9780102871,'On Speaking Well','Decorative Arts',1);
INSERT INTO Books VALUES (9780102872,'Gertrude Bell : Queen of the Desert, Shaper of Nations','Textile Artworks',8);
INSERT INTO Books VALUES (9780102873,'Adobe Flash Professional CS6 Classroom in a Book','Exhibition Catalogues and Specific Collections',2);
INSERT INTO Books VALUES (9780102874,'Practice Makes Perfect German Verb Tenses','Art Techniques and Principles',1);
INSERT INTO Books VALUES (9780102875,'Traveling with Ghosts : A Memoir','Photography',4);
INSERT INTO Books VALUES (9780102876,'Power Tools for Cubase 7 ','Photography',3);
INSERT INTO Books VALUES (9780102877,'Grammatically Correct ','Photography',6);
INSERT INTO Books VALUES (9780102878,'Antarctica''s Lost Aviator ','Photography',4);
INSERT INTO Books VALUES (9780102879,'Digital Photography For Dummies','Photography',7);
INSERT INTO Books VALUES (9780102880,'Grammar Bible','Individual Photographers',2);
INSERT INTO Books VALUES (9780102881,'A Walk for Sunshine : A 2,160-mile Expedition for Charity on the Appalachian Trail','Photographs: Collections',8);
INSERT INTO Books VALUES (9780102882,'OpenGL Programming Guide ','Photographs: Collections',8);
INSERT INTO Books VALUES (9780102883,'Voila (3rd edition) A French Course for Adult Beginners : Coursebook','Photographs: Collections',2);
INSERT INTO Books VALUES (9780102884,'On the Trail of Genghis Khan : An Epic Journey Through the Land of the Nomads','Photographs: Collections',1);
INSERT INTO Books VALUES (9780102885,'The One Hour Content Plan','Photographs: Collections',7);
INSERT INTO Books VALUES (9780102886,'Analysing Sentences : An Introduction to English Syntax','Photographs: Collections',5);
INSERT INTO Books VALUES (9780102887,'Walking to Listen : 4,000 Miles Across America, One Story at a Time','Photographs: Collections',3);
INSERT INTO Books VALUES (9780102888,'Facebook All-in-One For Dummies','Photographic Equipment and Techniques',8);
INSERT INTO Books VALUES (9780102889,'Irish Phrasebook','Photographic Equipment and Techniques',7);
INSERT INTO Books VALUES (9780102890,'Queen of the Road','Photographic Equipment and Techniques',9);
INSERT INTO Books VALUES (9780102891,'Make Your Own Pixel Art','Photographic Equipment and Techniques',6);
INSERT INTO Books VALUES (9780102892,'A World Without Whom','Photographic Equipment and Techniques',5);
INSERT INTO Books VALUES (9780102893,'The Only Street in Paris : Life on the Rue Des Martyrs','Cinematography, Television Camerawork',3);
INSERT INTO Books VALUES (9780102894,'Digital Painting Techniques Volume 8','Industrial / Commercial Art and Design',7);
INSERT INTO Books VALUES (9780102895,'Grammar Girl''s 101 Troublesome Words You''ll Master in No Time','Industrial / Commercial Art and Design',2);
INSERT INTO Books VALUES (9780102896,'The Pursuit of Italy : A History of a Land, Its Regions, and Their Peoples','Industrial / Commercial Art and Design',2);
INSERT INTO Books VALUES (9780102897,'Augmented Human','Industrial / Commercial Art and Design',6);
INSERT INTO Books VALUES (9780102898,'Finnish Tutor','Industrial / Commercial Art and Design',9);
INSERT INTO Books VALUES (9780102899,'Seattle Noir','Industrial / Commercial Art and Design',3);
INSERT INTO Books VALUES (9780102900,'Introducing Maya 2011','Industrial / Commercial Art and Design',7);
INSERT INTO Books VALUES (9780102901,'How to Behave Badly in Renaissance Britain','Industrial / Commercial Art and Design',1);
INSERT INTO Books VALUES (9780102902,'Great Exploration Hoaxes','Industrial / Commercial Art and Design',2);
INSERT INTO Books VALUES (9780102903,'Missional Communities : The Rise of the Post-Congregational Church','Industrial / Commercial Art and Design',4);
INSERT INTO Books VALUES (9780102904,'Oxford Academic Vocabulary Practice: Upper-Intermediate B2-C1: with Key','Industrial / Commercial Art and Design',3);
INSERT INTO Books VALUES (9780102905,'The Lost Continent','Industrial / Commercial Art and Design',3);
INSERT INTO Books VALUES (9780102906,'Little Town on the Prairie','Industrial / Commercial Art and Design',9);
INSERT INTO Books VALUES (9780102907,'Interface Design for Learning : Design Strategies for Learning Experiences','Industrial / Commercial Art and Design',10);
INSERT INTO Books VALUES (9780102908,'Falling Upwards Lib/E : How We Took to the Air','Industrial / Commercial Art and Design',9);
INSERT INTO Books VALUES (9780102909,'My Social Stories Book','Industrial / Commercial Art and Design',7);
INSERT INTO Books VALUES (9780102910,'Cinematic Art of StarCraft','Industrial / Commercial Art and Design',6);
INSERT INTO Books VALUES (9780102911,'The Living Great Lakes : Searching for the Heart of the Inland Seas','Graphic Design',1);
INSERT INTO Books VALUES (9780102912,'Dork Diaries: Tales from a Not-So-Best Friend Forever','Graphic Design',2);
INSERT INTO Books VALUES (9780102913,'LaTeX Quick Reference','Graphic Design',7);
INSERT INTO Books VALUES (9780102914,'Ten Years a Nomad : A Traveler''s Journey Home','Graphic Design',3);
INSERT INTO Books VALUES (9780102915,'Bart Simpson''s Guide to Life : A Wee Handbook for the Perplexed','Graphic Design',9);
INSERT INTO Books VALUES (9780102916,'Looking for Alaska','Typography and Lettering',2);
INSERT INTO Books VALUES (9780102917,'PHP for the Web : Visual QuickStart Guide','Comic Book and Cartoon Art',6);
INSERT INTO Books VALUES (9780102918,'Shakespeare''s Macbeth for Kids','Comic Book and Cartoon Art',10);
INSERT INTO Books VALUES (9780102919,'Monster Live: Dylan Moran','Product Design',9);
INSERT INTO Books VALUES (9780102920,'The Great Treehouse War','Product Design',9);
INSERT INTO Books VALUES (9780102921,'Storytelling for Virtual Reality ','Furniture Design',1);
INSERT INTO Books VALUES (9780102922,'Definitive Broadway Collection','Furniture Design',3);
INSERT INTO Books VALUES (9780102923,'A Pocketful of Python: v.1','Furniture Design',1);
INSERT INTO Books VALUES (9780102924,'I Survived the Japanese Tsunami, 2011 (I Survived #8)','Furniture Design',8);
INSERT INTO Books VALUES (9780102925,'Digital Compositing with Nuke','Furniture Design',3);
INSERT INTO Books VALUES (9780102926,'Thinking Like a Director : A Practical Handbook','Furniture Design',7);
INSERT INTO Books VALUES (9780102927,'Little Britain:Best Of TV Series 3','Furniture Design',7);
INSERT INTO Books VALUES (9780102928,'Germs are Not for Sharing','Furniture Design',6);
INSERT INTO Books VALUES (9780102929,'Digital Filmmaking for Beginners A Practical Guide to Video Production','Fashion and Textiles: Design',4);
INSERT INTO Books VALUES (9780102930,'Duo! : The Best Scenes for Two for the 21st Century','Fashion and Textiles: Design',6);
INSERT INTO Books VALUES (9780102931,'Will Smith Presents : The Tao of Bergerac','Fashion and Textiles: Design',7);
INSERT INTO Books VALUES (9780102932,'Wildwood','Fashion and Textiles: Design',8);
INSERT INTO Books VALUES (9780102933,'The Modern Web','Fashion and Textiles: Design',0);
INSERT INTO Books VALUES (9780102934,'The Secret History of Magic : The True Story of the Deceptive Art','Fashion and Textiles: Design',8);
INSERT INTO Books VALUES (9780102935,'TV Go Home','Fashion and Textiles: Design',2);
INSERT INTO Books VALUES (9780102936,'What''s a Girl Gotta Do?','Fashion and Textiles: Design',10);
INSERT INTO Books VALUES (9780102937,'Designing Web APIs : Building APIs That Developers Love','Fashion and Textiles: Design',0);
INSERT INTO Books VALUES (9780102938,'Paris Flea Market Style','Fashion and Textiles: Design',2);
INSERT INTO Books VALUES (9780102939,'The Grumbleweeds','Fashion and Textiles: Design',10);
INSERT INTO Books VALUES (9780102940,'Linux for Makers','Fashion and Textiles: Design',8);
INSERT INTO Books VALUES (9780102941,'The Hodgeheg','Fashion and Textiles: Design',3);
INSERT INTO Books VALUES (9780102942,'Imagine. Shoot. Create. : Creative Photography','Fashion and Textiles: Design',4);
INSERT INTO Books VALUES (9780102943,'Bali Home : Inspirational Design Ideas','Fashion and Textiles: Design',1);
INSERT INTO Books VALUES (9780102944,'Grumpy Old Christmas : N/A','Fashion and Textiles: Design',4);
INSERT INTO Books VALUES (9780102945,'More Goon Show Scripts','Fashion and Textiles: Design',1);
INSERT INTO Books VALUES (9780102946,'A Night Divided (Scholastic Gold)','Fashion and Textiles: Design',6);
INSERT INTO Books VALUES (9780102947,'The Micro Kids : An 80s Adventure with ZX Spectrum, Commodore 64 and more','Fashion and Textiles: Design',9);
INSERT INTO Books VALUES (9780102948,'English Country House Interiors','Fashion and Textiles: Design',8);
INSERT INTO Books VALUES (9780102949,'Breaking Bad Say My Name Badass Best Quotes','Fashion Design and Theory',1);
INSERT INTO Books VALUES (9780102950,'I''m A Celebrity... Get Me Out Of Here! The Inside Story','Fashion Design and Theory',6);
INSERT INTO Books VALUES (9780102951,'Emergency Contact','Fashion Design and Theory',7);
INSERT INTO Books VALUES (9780102952,'Rig it Right! Maya Animation Rigging Concepts, 2nd edition','Architecture',2);
INSERT INTO Books VALUES (9780102953,'Makeup Makeovers','Architecture',1);
INSERT INTO Books VALUES (9780102954,'The Three Stooges : See No Evil, Hear No Evil, Speak No Evil','Architecture',6);
INSERT INTO Books VALUES (9780102955,'The Secret Diary of a Grumpy Old Woman','Architecture',2);
INSERT INTO Books VALUES (9780102956,'The Spectacular Now','Individual Architects and Architectural Firms',6);
INSERT INTO Books VALUES (9780102957,'Adobe Photoshop Elements 8','Individual Architects and Architectural Firms',3);
INSERT INTO Books VALUES (9780102958,'Pierre Yovanovitch','Individual Architects and Architectural Firms',6);
INSERT INTO Books VALUES (9780102959,'Fawlty Towers : Second Sitting','Architectural Structure and Design',10);
INSERT INTO Books VALUES (9780102960,'Victoria Wood Collection','Environmentally-friendly Architecture and Design',3);
INSERT INTO Books VALUES (9780102961,'The Going to Bed Book','Residential Buildings, Domestic Buildings',6);
INSERT INTO Books VALUES (9780102962,'Hacks for Minecrafters','Professional Interior Design',7);
INSERT INTO Books VALUES (9780102963,'Bright Lights Paris : Shop, Dine and Live...Parisian Style','Professional Interior Design',4);
INSERT INTO Books VALUES (9780102964,'I, Partridge: We Need To Talk About Alan','Professional Interior Design',1);
INSERT INTO Books VALUES (9780102965,'Ned Flanders'' Book of Faith','Professional Interior Design',6);
INSERT INTO Books VALUES (9780102966,'LGB Tootle','Professional Interior Design',1);
INSERT INTO Books VALUES (9780102967,'Linked Data','Professional Interior Design',3);
INSERT INTO Books VALUES (9780102968,'Ayurvedic Beauty Care : Ageless Techniques to Invoke Natural Beauty','Professional Interior Design',3);
INSERT INTO Books VALUES (9780102969,'Official DCI Gene Hunt Calendar 2012','Professional Interior Design',5);
INSERT INTO Books VALUES (9780102970,'Official Family Guy Block Calendar 2012','Professional Interior Design',8);
INSERT INTO Books VALUES (9780102971,'Pretty Little Liars #4: Unbelievable','Professional Interior Design',8);
INSERT INTO Books VALUES (9780102972,'Advanced Photoshop Elements 7 for Digital Photographers','Professional Interior Design',9);
INSERT INTO Books VALUES (9780102973,'skinCARE : The Ultimate No-Nonsense Guide','Professional Interior Design',7);
INSERT INTO Books VALUES (9780102974,'1001 Reasons Why Eastenders is Pony!','Professional Interior Design',9);
INSERT INTO Books VALUES (9780102975,'Fawlty Towers','Professional Interior Design',7);
INSERT INTO Books VALUES (9780102976,'Instant Monty Python','Professional Interior Design',3);
INSERT INTO Books VALUES (9780102977,'The Complete Philosophy Files','Professional Interior Design',5);
INSERT INTO Books VALUES (9780102978,'Data Visualization With Javascript','Professional Interior Design',5);
INSERT INTO Books VALUES (9780102979,'Cabana: Anthology','Professional Interior Design',3);
INSERT INTO Books VALUES (9780102980,'The Parisian Gentleman','Professional Interior Design',3);
INSERT INTO Books VALUES (9780102981,'Classic Tailoring Techniques : A Construction Guide for Women''s Wear','Theatre Studies',5);
INSERT INTO Books VALUES (9780102982,'How to be Like Walt : Capturing the Disney Magic Every Day of Your Life','Theatre Studies',2);
INSERT INTO Books VALUES (9780102983,'Magical Mermaids! (Shimmer and Shine)','Theatre Studies',9);
INSERT INTO Books VALUES (9780102984,'Meta Products : Building the Internet of Things','Theatre Direction and Production',5);
INSERT INTO Books VALUES (9780102985,'Facial Gua Sha : A Step-by-step Guide to a Natural Facelift','Celebrity Biographies and Books',7);
INSERT INTO Books VALUES (9780102986,'Beauty and Cosmetics 1550 to 1950','Celebrity Biographies and Books',7);
INSERT INTO Books VALUES (9780102987,'Tokyo','Film Theory and Criticism',6);
INSERT INTO Books VALUES (9780102988,'Jeff Leatham : Revolutionary Floral Art and Design','Television',2);
INSERT INTO Books VALUES (9780102989,'Each Breath A Smile','Television',3);
INSERT INTO Books VALUES (9780102990,'Rowland B. Wilson''s Trade Secrets : Notes on Cartooning and Animation','Television',8);
INSERT INTO Books VALUES (9780102991,'Inspired Bead Embroidery : New jewelry designs by Sherry Serafini','Television',1);
INSERT INTO Books VALUES (9780102992,'Georgia O''Keeffe: Living Modern','Radio Scripts',2);
INSERT INTO Books VALUES (9780102993,'Timeless Beadwork Designs','Electronic Music',8);
INSERT INTO Books VALUES (9780102994,'Do Less : A Minimalist Guide to a Simplified, Organized, and Happy Life','Individual Composers and Musicians, Specific Bands and Groups',5);
INSERT INTO Books VALUES (9780102995,'Identical','Biography: General',7);
INSERT INTO Books VALUES (9780102996,'Practical Object-Oriented Design With Uml','Biography: General',5);
INSERT INTO Books VALUES (9780102997,'Millie Marotta''s Home Sticker Book','Biography: General',4);
INSERT INTO Books VALUES (9780102998,'Creative Haven Terrific Tessellations Coloring Book','Biography: General',10);
INSERT INTO Books VALUES (9780102999,'Paper Crafts: The Joy of Card Making','Biography: General',3);
INSERT INTO Books VALUES (9780103000,'150 Best New Eco Home Ideas','Biography: General',8);
INSERT INTO Books VALUES (9780103001,'I Funny : A Middle School Story','Biography: General',7);
INSERT INTO Books VALUES (9780103002,'Adobe Photoshop Elements 11 for Photographers ','Biography: General',0);
INSERT INTO Books VALUES (9780103003,'Minimal : How to simplify your life and live sustainably','Biography: General',5);
INSERT INTO Books VALUES (9780103004,'London Precincts ','Biography: General',6);
INSERT INTO Books VALUES (9780103005,'Poems and Readings for Weddings','Biography: Arts and Entertainment',2);
INSERT INTO Books VALUES (9780103006,'Axel Vervoordt: Stories and Reflections','Biography: Arts and Entertainment',0);
INSERT INTO Books VALUES (9780103007,'Something Beautiful','Biography: Historical, Political and Military',6);
INSERT INTO Books VALUES (9780103008,'AutoCAD 2017 and AutoCAD LT 2017 Essentials','Biography: Historical, Political and Military',6);
INSERT INTO Books VALUES (9780103009,'Imperfect Home','Biography: Historical, Political and Military',1);
INSERT INTO Books VALUES (9780103010,'Keep it Simple : A Guide to a Happy, Relaxed Home','Biography: Literary',7);
INSERT INTO Books VALUES (9780103011,'A Place to Call Home : Tradition, style, and memory in the new American house','Diaries, Letters and Journals',6);
INSERT INTO Books VALUES (9780103012,'Makeup Artist Face Charts','Memoirs',10);
INSERT INTO Books VALUES (9780103013,'Sheila Rae, the Brave','Memoirs',9);
INSERT INTO Books VALUES (9780103014,'Web Animation using JavaScript : Develop and Design','Memoirs',1);
INSERT INTO Books VALUES (9780103015,'Victorian and Edwardian Fashions from La Mode Illustree','Memoirs',7);
INSERT INTO Books VALUES (9780103016,'Her Mother''s Secret','True Crime Biographies',9);
INSERT INTO Books VALUES (9780103017,'Mind Over Clutter : Cleaning Your Way to a Calm and Happy Home','Language: Reference and General',5);
INSERT INTO Books VALUES (9780103018,'Luxurious Bath Bombs','Language: Reference and General',4);
INSERT INTO Books VALUES (9780103019,'All''s Faire In Middle School','Language: Reference and General',10);
INSERT INTO Books VALUES (9780103020,'The HDR Book : Unlocking the Pros'' Hottest Post-Processing Techniques','Usage and Grammar Guides',3);
INSERT INTO Books VALUES (9780103021,'The Absolute Beginners Guide: Jewelry Making with Resin','Usage and Grammar Guides',8);
INSERT INTO Books VALUES (9780103022,'How to Work a Room','Usage and Grammar Guides',3);
INSERT INTO Books VALUES (9780103023,'Inspired You : Breathing New Life into Your Heart and Home','Usage and Grammar Guides',7);
INSERT INTO Books VALUES (9780103024,'Feed Your Face : Younger, Smoother Skin and a Beautiful Body in 28 Delicious Days','Usage and Grammar Guides',4);
INSERT INTO Books VALUES (9780103025,'Mission Survival 7: Rage of the Rhino','Usage and Grammar Guides',8);
INSERT INTO Books VALUES (9780103026,'Bootstrap Reference Guide : Bootstrap 4 and 3 Cheat Sheets Collection','Usage and Grammar Guides',1);
INSERT INTO Books VALUES (9780103027,'The Fashion Designer''s Textile Directory ','Usage and Grammar Guides',9);
INSERT INTO Books VALUES (9780103028,'Wagashi : Handcrafted Fashion Art from Japan','Usage and Grammar Guides',4);
INSERT INTO Books VALUES (9780103029,'Advanced Chain Maille Jewelry Workshop : Weaving with Rings and Scale Maille','Usage and Grammar Guides',1);
INSERT INTO Books VALUES (9780103030,'Chic and Slim : How Those Chic French Women Eat All That Rich Food and Still Stay Slim','Usage and Grammar Guides',4);
INSERT INTO Books VALUES (9780103031,'Mama Do You Love Me? Board Book','Usage and Grammar Guides',6);
INSERT INTO Books VALUES (9780103032,'Automating with SIMATIC S7-1500 : Configuring, Programming and Testing with STEP 7 Professional','Usage and Grammar Guides',8);
INSERT INTO Books VALUES (9780103033,'How to be Adored','Usage and Grammar Guides',7);
INSERT INTO Books VALUES (9780103034,'Dior Glamour : 1952-1962','Usage and Grammar Guides',10);
INSERT INTO Books VALUES (9780103035,'Art and Makeup','Usage and Grammar Guides',10);
INSERT INTO Books VALUES (9780103036,'Vietnam - Culture Smart! : The Essential Guide to Customs and Culture','Creative Writing and Creative Writing Guides',7);
INSERT INTO Books VALUES (9780103037,'The Sun is also a Star','Language Teaching and Learning Material and Coursework',1);
INSERT INTO Books VALUES (9780103038,'The Strategic Web Designer : How to Confidently Navigate the Web Design Process','Poetry Anthologies (various Poets)',0);
INSERT INTO Books VALUES (9780103039,'Cutting Hair the Vidal Sassoon Way','Literary Essays',0);
INSERT INTO Books VALUES (9780103040,'Thomas Pheasant : Simply Serene','Anthologies (non-poetry)',3);
INSERT INTO Books VALUES (9780103041,'Decorating with Plants : The Art of Using Plants to Transform Your Home','Literary Theory',7);
INSERT INTO Books VALUES (9780103042,'Kitchen and Bath Renovation Guide','ELT: Learning Material and Coursework',8);
INSERT INTO Books VALUES (9780103043,'The 7 Habits Of Highly Effective Teenagers','World War 1 Fiction',4);
INSERT INTO Books VALUES (9780103044,'Design for Communication : Conceptual Graphic Design Basics','Reference Books',3);
INSERT INTO Books VALUES (9780103045,'Feeling Good About the Way You Look : A Program for Overcoming Body Image Problems','Reference Works',4);
INSERT INTO Books VALUES (9780103046,'Unmentionable : The Victorian Lady''s Guide to Sex, Marriage, and Manners','Reference Works',5);
INSERT INTO Books VALUES (9780103047,'Modern Quilting : 25 Step-by-Step Projects for Cool and Contemporary Patchwork and Quilts','Reference Works',1);
INSERT INTO Books VALUES (9780103048,'Classic Fashion Patterns of the 20th century : Make your own vintage clothing','Reference Works',9);
INSERT INTO Books VALUES (9780103049,'Magic Tree House Fact Tracker #14 Ancient Rome and Pompeii','Reference Works',4);
INSERT INTO Books VALUES (9780103050,'Systems Science and Modeling for Ecological Economics','Reference Works',4);
INSERT INTO Books VALUES (9780103051,'Cut Flowers : A Practical Guide to their Selection and Care','Information Theory',3);
INSERT INTO Books VALUES (9780103052,'A Well-Crafted Home : Inspiration and 60 Projects for Personalizing your Space','Information Theory',4);
INSERT INTO Books VALUES (9780103053,'Le Petit Wedding Book','Society and Culture: General',7);
INSERT INTO Books VALUES (9780103054,'The New French Decor','Popular Culture',2);
INSERT INTO Books VALUES (9780103055,'Molly Moon''s Hypnotic Time Travel Adventure','Popular Culture',8);
INSERT INTO Books VALUES (9780103056,'Problems and Solutions in Biological Sequence Analysis','Popular Culture',1);
INSERT INTO Books VALUES (9780103057,'Dress in Anglo-Saxon England','Media Studies',5);
INSERT INTO Books VALUES (9780103058,'Creating the Not So Big House','Feminism and Feminist Theory',2);
INSERT INTO Books VALUES (9780103059,'Akira Isogawa:Unfolding a Life in Fashion : Unfolding a Life in Fashion','Age Groups: Children',10);
INSERT INTO Books VALUES (9780103060,'Cloud Busting','Sociology and Anthropology',2);
INSERT INTO Books VALUES (9780103061,'Facebook for Beginners in Easy Steps','Sociology: Customs and Traditions',5);
INSERT INTO Books VALUES (9780103062,'How One of You Can Bring the Two of You Together','Sociology: Death and Dying',6);
INSERT INTO Books VALUES (9780103063,'The Kitchn Cookbook : Recipes, Kitchens and Tips to Inspire Your Cooking','Social Work',6);
INSERT INTO Books VALUES (9780103064,'Petite Places : Clever Interiors for Humble Homes','Psychology',9);
INSERT INTO Books VALUES (9780103065,'Tudor Fashion','Psychology',0);
INSERT INTO Books VALUES (9780103066,'Alpha Force: Rat-Catcher : Book 2','Cognitivism, Cognitive Theory',1);
INSERT INTO Books VALUES (9780103067,'Introduction to Deep Learning : From Logical Calculus to Artificial Intelligence','Social, Group Or Collective Psychology',8);
INSERT INTO Books VALUES (9780103068,'Diane Keaton House','Social, Group Or Collective Psychology',6);
INSERT INTO Books VALUES (9780103069,'Beautiful Body, Beautiful Mind : The Power of Positive Imagery','Abnormal Psychology',4);
INSERT INTO Books VALUES (9780103070,'You Have the Right to Remain Fat','Industrial Or Vocational Training',2);
INSERT INTO Books VALUES (9780103071,'Living with Color : Inspiration and How-Tos to Brighten Up Your Home','Industrial Or Vocational Training',3);
INSERT INTO Books VALUES (9780103072,'What You Do Matters','Teaching Of Specific Groups and Persons With Special Educational Needs',3);
INSERT INTO Books VALUES (9780103073,'Editing Digital Video','Domestic Trade',5);
INSERT INTO Books VALUES (9780103074,'A Sense of Home : Eat - Make - Sleep - Live','Business and Management',2);
INSERT INTO Books VALUES (9780103075,'The Language of Fashion','Business and Management',0);
INSERT INTO Books VALUES (9780103076,'Eye Candy','Business and Management',0);
INSERT INTO Books VALUES (9780103077,'The Happy Closet','Business Strategy',4);
INSERT INTO Books VALUES (9780103078,'Love Letters to the Dead','E-commerce: Business Aspects',4);
INSERT INTO Books VALUES (9780103079,'The Complete E-Commerce Book : Design, Build and Maintain a Successful Web-based Business','E-commerce: Business Aspects',1);
INSERT INTO Books VALUES (9780103080,'Chic and Slim Encore : More about How French Women Dress Chic Stay Slim-And How You Can Too','E-commerce: Business Aspects',8);
INSERT INTO Books VALUES (9780103081,'Surf Like a Girl','Management and Management Techniques',5);
INSERT INTO Books VALUES (9780103082,'Guerilla Furniture Design','Business Communication and Presentation',6);
INSERT INTO Books VALUES (9780103083,'The Hands-On Home','Distributive Industries',9);
INSERT INTO Books VALUES (9780103084,'The Survival Guide for Gifted Kids','Epidemiology and Medical Statistics',2);
INSERT INTO Books VALUES (9780103085,'Never Use Pop Up Windows : And 50 Other Ridiculous Web Rules','Clinical and Internal Medicine',5);
INSERT INTO Books VALUES (9780103086,'Sunday Sews : 20 Inspired Weekend Projects','Pharmacology',10);
INSERT INTO Books VALUES (9780103087,'A Kids'' Guide to Manners : 50 Fun Etiquette Lessons for Kids (and Their Families)','Complementary Medicine',1);
INSERT INTO Books VALUES (9780103088,'Faberge : His Masters and Artisans','History Of Science',5);
INSERT INTO Books VALUES (9780103089,'Nordic Moods : A Guide to Successful Interior Decoration','Ecological Science, The Biosphere',2);
INSERT INTO Books VALUES (9780103090,'The Baby Tree','Genetics (non-medical)',6);
INSERT INTO Books VALUES (9780103091,'Digital Design Exercises for Architecture Students','Sustainability',7);
INSERT INTO Books VALUES (9780103092,'Chain And Bead Jewelry Creative Connections','Sustainability',9);
INSERT INTO Books VALUES (9780103093,'Bio-Young : Get Younger at a Cellular and Hormonal Level','Sustainability',0);
INSERT INTO Books VALUES (9780103094,'Kimono : A Modern History','Sustainability',4);
INSERT INTO Books VALUES (9780103095,'HomeMade Modern : Smart DIY Designs for a Stylish Home','Engineering: General',8);
INSERT INTO Books VALUES (9780103096,'Why I Sneeze, Shiver, Hiccup and Yawn','Biochemical Engineering',8);
INSERT INTO Books VALUES (9780103097,'Software Essentials for Graphic Designers ','Mechanical Engineering',9);
INSERT INTO Books VALUES (9780103098,'Less : A Visual Guide to Minimalism','Electronics Engineering',5);
INSERT INTO Books VALUES (9780103099,'Essential Oils Book','Electronics Engineering',8);
INSERT INTO Books VALUES (9780103100,'Veere Grenney : On Decorating: A Point of View','Automatic Control Engineering',4);
INSERT INTO Books VALUES (9780103101,'Decorating In Detail','Robotics',6);
INSERT INTO Books VALUES (9780103102,'Love and Gelato','Building Skills and Trades',0);
INSERT INTO Books VALUES (9780103103,'Pro ASP.NET 2.0 E-Commerce in C# 2005','Hotel and Catering Trades',6);
INSERT INTO Books VALUES (9780103104,'Kinfolk Volume 28','Computing: General',2);
INSERT INTO Books VALUES (9780103105,'Colored Pencil on Copper Jewelry : Enhance Your Metalwork the Easy Way','Digital Lifestyle',9);
INSERT INTO Books VALUES (9780103106,'Inspired Home : Nests of Creatives','Digital Lifestyle',6);
INSERT INTO Books VALUES (9780103107,'The Magical and Ritual Use of Perfumes','Digital Lifestyle',5);
INSERT INTO Books VALUES (9780103108,'The Boxcar Children Bookshelf (Books #1-12)','Internet Guides and Online Services',1);
INSERT INTO Books VALUES (9780103109,'The Principles and Processes of Interactive Design','Internet Guides and Online Services',8);
INSERT INTO Books VALUES (9780103110,'The Little Guide To Vintage Shopping','Internet Guides and Online Services',8);
INSERT INTO Books VALUES (9780103111,'Life Honestly : Strong Opinions from Smart Women','Internet Guides and Online Services',9);
INSERT INTO Books VALUES (9780103112,'The Englishman''s Suit','Internet Guides and Online Services',1);
INSERT INTO Books VALUES (9780103113,'The Domino Decorating Books Box Set : The Book of Decorating and Your Guide to a Stylish Home','Digital TV and Media Centres: Consumer/user Guides',0);
INSERT INTO Books VALUES (9780103114,'If I Could Keep You Little','Games Strategy Guides',7);
INSERT INTO Books VALUES (9780103115,'Learning Microsoft Publisher 2013, Student Edition -- CTE/School','Business Applications',5);
INSERT INTO Books VALUES (9780103116,'Hats : A History of Fashion in Headwear','Business Applications',3);
INSERT INTO Books VALUES (9780103117,'True Style is What''s Underneath','Business Applications',1);
INSERT INTO Books VALUES (9780103118,'Dream Rooms: Inspirational Interiors from 100 Homes','Business Applications',4);
INSERT INTO Books VALUES (9780103119,'Mi Diario de Yoga','Enterprise Software',8);
INSERT INTO Books VALUES (9780103120,'Pirate Potty','Enterprise Software',9);
INSERT INTO Books VALUES (9780103121,'Multimedia Programming Using Max/MSP and TouchDesigner','Graphical and Digital Media Applications',4);
INSERT INTO Books VALUES (9780103122,'The Thoughtful Dresser','Graphical and Digital Media Applications',9);
INSERT INTO Books VALUES (9780103123,'Cultivating Inner Peace','Graphical and Digital Media Applications',10);
INSERT INTO Books VALUES (9780103124,'A Parisian Cabinet of Curiosities: Deyrolle','Graphical and Digital Media Applications',3);
INSERT INTO Books VALUES (9780103125,'Crash into You','Graphical and Digital Media Applications',3);
INSERT INTO Books VALUES (9780103126,'GoPro Hero and Fusion Guide : How to Use your GoPro Fusion, Hero 4/5/6/7 Stock, White, and Black','Graphical and Digital Media Applications',4);
INSERT INTO Books VALUES (9780103127,'Winter Wonderland 500 Piece Puzzle','Web Graphics and Design',8);
INSERT INTO Books VALUES (9780103128,'The Mitford Girls'' Guide to Life','Web Graphics and Design',10);
INSERT INTO Books VALUES (9780103129,'The Perricone Weight-Loss Diet : A Simple 3-Part Plan to Lose the Fat, the Wrinkles, and the Years','Web Graphics and Design',6);
INSERT INTO Books VALUES (9780103130,'Salud De La Botica Del Senor','Web Graphics and Design',7);
INSERT INTO Books VALUES (9780103131,'The Legacy Chronicles: Trial by Fire','Web Graphics and Design',9);
INSERT INTO Books VALUES (9780103132,'Eye Tracking Methodology : Theory and Practice','Web Graphics and Design',5);
INSERT INTO Books VALUES (9780103133,'The Crystal Code : Balance Your Energy, Transform Your Life','Web Graphics and Design',6);
INSERT INTO Books VALUES (9780103134,'Concrete Crafts : Making Modern Accessories for the Home and Garden','Web Graphics and Design',10);
INSERT INTO Books VALUES (9780103135,'London Stitch + Knit: A Craft Lover''s Guide to London''s Fabric, Knitting and Haberdashery Shops','Web Graphics and Design',7);
INSERT INTO Books VALUES (9780103136,'The Paris Style Guide : Shop, Eat, Sleep','Web Graphics and Design',8);
INSERT INTO Books VALUES (9780103137,'Pinkie Pie and the Rockin'' Ponypalooza Party!','Web Graphics and Design',3);
INSERT INTO Books VALUES (9780103138,'Jim Blinn''s Corner: A Trip Down the Graphics Pipeline','Web Graphics and Design',4);
INSERT INTO Books VALUES (9780103139,'Hausmagick : Transform Your Home with Witchcraft','Web Graphics and Design',2);
INSERT INTO Books VALUES (9780103140,'How Not to Wear Black','Computer-aided Design (CAD)',8);
INSERT INTO Books VALUES (9780103141,'Class with the Countess : How to Live with Elegance and Flair','3D Graphics and Modelling',8);
INSERT INTO Books VALUES (9780103142,'Manskills : How to Avoid Embarrassing Yourself and Impress Everyone Else','Digital Animation',1);
INSERT INTO Books VALUES (9780103143,'Little Critter The New Potty','Baby Books',0);
INSERT INTO Books VALUES (9780103144,'Scandinavian Gatherings : From Afternoon Fika To Midsummer Feast','Early Learning',3);
INSERT INTO Books VALUES (9780103145,'Home-Made Europe : Contemporary Folk Artifacts','Early Learning',7);
INSERT INTO Books VALUES (9780103146,'Atomic Ranch: Midcentury Interiors','Early Learning',6);
INSERT INTO Books VALUES (9780103147,'The Set Table : The Art of Small Gatherings','First Words',9);
INSERT INTO Books VALUES (9780103148,'The Fault in Our Stars','Poetry Books for Kids',6);
INSERT INTO Books VALUES (9780103149,'RESTful Web API Design with Node.js 10','Children''s Fiction',4);
INSERT INTO Books VALUES (9780103150,'The Magical Year','Children''s Fiction',4);
INSERT INTO Books VALUES (9780103151,'Beauty by Nature : Complete Body Care','Children''s Fiction',8);
INSERT INTO Books VALUES (9780103152,'You Can Wear it Again','Children''s Fiction',8);
INSERT INTO Books VALUES (9780103153,'64 DIY natural beauty recipes : How to Make Amazing Homemade Skin Care Recipes, Essential Oils, Body Care Products and More','Children''s Fiction',7);
INSERT INTO Books VALUES (9780103154,'The Arc of a Scythe Trilogy : Scythe; Thunderhead; The Toll','Children''s Fiction',1);
INSERT INTO Books VALUES (9780103155,'E-Learning Uncovered : Adobe Captivate 6','Children''s Fiction',9);
INSERT INTO Books VALUES (9780103156,'Philip Treacy by Kevin Davies','Children''s Fiction',9);
INSERT INTO Books VALUES (9780103157,'Great English Interiors','Children''s Fiction',1);
INSERT INTO Books VALUES (9780103158,'Fashions in Hair : The First Five Thousand Years','Children''s Fiction',8);
INSERT INTO Books VALUES (9780103159,'Small Space Style : Clever Ideas for Compact Interiors','Children''s Fiction',3);
INSERT INTO Books VALUES (9780103160,'Each Little Bird That Sings','Children''s Fiction',3);
INSERT INTO Books VALUES (9780103161,'Digital Storytelling 4e : A creator''s guide to interactive entertainment','Children''s Fiction',8);
INSERT INTO Books VALUES (9780103162,'The Art Of The Handwritten Note : A Guide to Reclaiming Civilized Communication','Children''s Fiction',3);
INSERT INTO Books VALUES (9780103163,'The Fashion System','Children''s Fiction',6);
INSERT INTO Books VALUES (9780103164,'Let''s Get Fizzical : Over 50 Bubbly Cocktail Recipes with Prosecco, Champagne, and other Sparkling Wines','Children''s Fiction',5);
INSERT INTO Books VALUES (9780103165,'Flea Market Style','Children''s Fiction',8);
INSERT INTO Books VALUES (9780103166,'Going Bovine','Children''s Fiction',5);
INSERT INTO Books VALUES (9780103167,'Principles of Web Design','Children''s Fiction',10);
INSERT INTO Books VALUES (9780103168,'Natural Beauty Basics : Create Your Own Cosmetics and Body Care Products','Children''s Fiction',5);
INSERT INTO Books VALUES (9780103169,'How to Turn Your Faith Loose','Children''s Fiction',4);
INSERT INTO Books VALUES (9780103170,'English Arts and Crafts Furniture : Projects and Techniques for the Modern Maker','Children''s Fiction',3);
INSERT INTO Books VALUES (9780103171,'Pretty Gentlemen : Macaroni Men and the Eighteenth-Century Fashion World','Children''s Fiction',5);
INSERT INTO Books VALUES (9780103172,'Fancy Nancy: 5-Minute Fancy Nancy Stories','Children''s Fiction',1);
INSERT INTO Books VALUES (9780103173,'Photoshop Elements Made Easy : Enhance Your Memories With Ease','Children''s Fiction',0);
INSERT INTO Books VALUES (9780103174,'The Art of the White Shirt : Over 30 Ways to Wear a White T-Shirt, Blouse or Shirt','Children''s Fiction',5);
INSERT INTO Books VALUES (9780103175,'Parish-Hadley Tree of Life : An Intimate History of the Legendary Design Firm','Children''s Fiction',6);
INSERT INTO Books VALUES (9780103176,'Etiquette Guide to Korea : Know the Rules That Make the Difference!','Children''s Fiction',7);
INSERT INTO Books VALUES (9780103177,'La Terapia Gerson : El Programa Nutricional Definitivo Para Salvar Vidas','Children''s Fiction',8);
INSERT INTO Books VALUES (9780103178,'Borrowers Afloat','Children''s Fiction',7);
INSERT INTO Books VALUES (9780103179,'Rails: Up and Running','Children''s Fiction',3);
INSERT INTO Books VALUES (9780103180,'Worn On This Day : The Clothes That Made History','Children''s Fiction',5);
INSERT INTO Books VALUES (9780103181,'Why Manners Matter : What Confucius, Jefferson, and Jackie O Knew and You Shouldtoo','Children''s Fiction',8);
INSERT INTO Books VALUES (9780103182,'Martha Stewart Weddings','Children''s Fiction',9);
INSERT INTO Books VALUES (9780103183,'How to Raise a Gentleman Revised and Expanded : A Civilized Guide to Helping Your Son Through His Uncivilized Childhood','Children''s Fiction',1);
INSERT INTO Books VALUES (9780103184,'Playtime for Twins','Children''s Fiction',7);
INSERT INTO Books VALUES (9780103185,'Future-Proof Web Design','Children''s Fiction',5);
INSERT INTO Books VALUES (9780103186,'Log Cabin Variations : 9 Stunning Log Cabin Projects','Children''s Fiction',3);
INSERT INTO Books VALUES (9780103187,'William Yeoward Perfect Tables : Tabletop Secrets, Settings and Centrepieces for Delicious Dining','Children''s Fiction',3);
INSERT INTO Books VALUES (9780103188,'The Collagen Diet : A 28-Day Plan for Sustained Weight Loss, Glowing Skin, Great Gut Health, and a Younger You','Classic Books for Children',9);
INSERT INTO Books VALUES (9780103189,'Classic Beauty: The History of Makeup','Classic Books for Children',3);
INSERT INTO Books VALUES (9780103190,'Hallowed','Children''s General Story Books',8);
INSERT INTO Books VALUES (9780103191,'The Art Of Interactive Design','Children''s General Story Books',6);
INSERT INTO Books VALUES (9780103192,'The Suit : Form, Function and Style','Children''s General Story Books',1);
INSERT INTO Books VALUES (9780103193,'Gentlewoman : Etiquette for a Lady, from a Gentleman','Children''s General Story Books',10);
INSERT INTO Books VALUES (9780103194,'Great War Fashion : Tales from the History Wardrobe','Children''s General Story Books',1);
INSERT INTO Books VALUES (9780103195,'Shoe Obsession','Children''s General Story Books',8);
INSERT INTO Books VALUES (9780103196,'Henry and the Clubhouse','Adventure Books for Kids',3);
INSERT INTO Books VALUES (9780103197,'Photoshop CS4 QuickSteps','Adventure Books for Kids',9);
INSERT INTO Books VALUES (9780103198,'Romania - Culture Smart! : The Essential Guide to Customs and Culture','Adventure Books for Kids',8);
INSERT INTO Books VALUES (9780103199,'Elements Of Wit : Mastering the Art of Being Interesting','Adventure Books for Kids',0);
INSERT INTO Books VALUES (9780103200,'Egypt - Culture Smart! : The Essential Guide to Customs and Culture','Adventure Books for Kids',1);
INSERT INTO Books VALUES (9780103201,'Wedding Planning For Dummies','Adventure Books for Kids',10);
INSERT INTO Books VALUES (9780103202,'Sinner','Romance Books for Teenagers',6);
INSERT INTO Books VALUES (9780103203,'Making an Impact Online : Creating a Website That Really Works without Breaking the Bank','Romance Books for Teenagers',1);
INSERT INTO Books VALUES (9780103204,'Oman - Culture Smart! : The Essential Guide to Customs and Culture','Romance Books for Teenagers',4);
INSERT INTO Books VALUES (9780103205,'Glass Kiln Casting : with Colour de Verre','Family',10);
INSERT INTO Books VALUES (9780103206,'50 Things I Wish I''d Told You : Life Skills','People and Places',4);
INSERT INTO Books VALUES (9780103207,'La obra completa sobre el vinyasa yoga/ The Complete Book of Vinyasa Yoga','Jokes and Humour',6);
INSERT INTO Books VALUES (9780103208,'The Mara Dyer Trilogy : The Unbecoming of Mara Dyer; The Evolution of Mara Dyer; The Retribution of Mara Dyer','Mysteries and The Supernatural (Children''s/YA)',10);
INSERT INTO Books VALUES (9780103209,'Foundation Website Creation with HTML5, CSS3, and JavaScript','English Language: Reading Schemes',1);
INSERT INTO Books VALUES (9780103210,'Yoga Con Cuentos','Society and Social Issues',8);
INSERT INTO Books VALUES (9780103211,'Decorative Doorways Stained Glass Pattern Book: 151 Designs for Sidelights, Fanlights, Transoms, etc. : 151 Designs for Sidelights, Fanlights, Transoms, etc.','Children''s Health Books',2);
INSERT INTO Books VALUES (9780103212,'Fabric Blooms : 42 Flowers to Make, Wear and Adorn Your Life','European History',8);
INSERT INTO Books VALUES (9780103213,'The Art of Shaving : Shaving Made Easy - What the man who shaves ought to know.','European History',2);
INSERT INTO Books VALUES (9780103214,'Showing Off (Upside-Down Magic #3)','British and Irish History',2);
INSERT INTO Books VALUES (9780103215,'Learning Autodesk Inventor 2020','Asian History',4);
INSERT INTO Books VALUES (9780103216,'Handmade Interiors : Make Your Own Cushions, Blinds and Other Soft Furnishings','African History',3);
INSERT INTO Books VALUES (9780103217,'Casa Mexico : At Home in Merida and the Yucatan','History Of The Americas',0);
INSERT INTO Books VALUES (9780103218,'How the French Live : Modern French Style','History Of The Americas',1);
INSERT INTO Books VALUES (9780103219,'NLP for Children','Modern History To 20th Century: C 1700 To C 1900',1);
INSERT INTO Books VALUES (9780103220,'Working with Video Gamers and Games in Therapy : A Clinician''s Guide','Health Books',1);
INSERT INTO Books VALUES (9780103221,'The Groom''s Secret Handbook : How Not to Screw up the Biggest Day of Her Life','Health Books',6);
INSERT INTO Books VALUES (9780103222,'Room and Furniture Layout Kit','Health Books',0);
INSERT INTO Books VALUES (9780103223,'Magical Fashionista : Dress for the Life You Want','Popular Medicine and Health',3);
INSERT INTO Books VALUES (9780103224,'Simple Stunning Weddings','Popular Medicine and Health',0);
INSERT INTO Books VALUES (9780103225,'The Night Diary','Coping With Personal Problems',5);
INSERT INTO Books VALUES (9780103226,'Builders of the Vision : Software and the Imagination of Design','Coping With Old Age',8);
INSERT INTO Books VALUES (9780103227,'The Complete Guide To Baby Naming Ceremonies','Coping With Old Age',10);
INSERT INTO Books VALUES (9780103228,'Dos and Don''ts Book 2! : Over a Thousand More Zings, Burns and Riffs from the Pages of Vice Magazine','Coping With Old Age',9);
INSERT INTO Books VALUES (9780103229,'The Big Shift : Navigating the New Stage Beyond Midlife','Diets and Dieting',6);
INSERT INTO Books VALUES (9780103230,'Top-Sy Turvy : 5 Crochet Sweaters for Girls'' Sizes 2-10','Diets and Dieting',9);
INSERT INTO Books VALUES (9780103231,'Little Miss Birthday','Diets and Dieting',7);
INSERT INTO Books VALUES (9780103232,'Mastering Search Analytics : Measuring Seo, SEM and Site Search','Exercise and Workout Books',4);
INSERT INTO Books VALUES (9780103233,'Your Best Home : 5 x Spaces x 5 Design Steps = a Better Life','Exercise and Workout Books',7);
INSERT INTO Books VALUES (9780103234,'Madder Anthology 1 : Camilla, Sibella, Imogen, and Beatrice','Exercise and Workout Books',8);
INSERT INTO Books VALUES (9780103235,'Fortuny Interiors','Family and Relationships',6);
INSERT INTO Books VALUES (9780103236,'The Wicker King','Dating, Relationships, Living Together and Marriage',8);
INSERT INTO Books VALUES (9780103237,'Building Flash Web Sites For Dummies','Dating, Relationships, Living Together and Marriage',0);
INSERT INTO Books VALUES (9780103238,'Men''s Fashion Illustrations from the Turn of the Century','Intergenerational Relationships',1);
INSERT INTO Books VALUES (9780103239,'Beaded Jewelry: Knotting Techniques','Advice On Parenting',6);
INSERT INTO Books VALUES (9780103240,'Consumer Behaviour : A European Perspective','Advice On Parenting',4);
INSERT INTO Books VALUES (9780103241,'Hanukkah in a Book (UpLifting Editions): Jacket comes off. Candles pop up. Display and celebrate!','Teenagers: Advice For Parents',2);
INSERT INTO Books VALUES (9780103242,'Wolf in the Snow','Personal Development',8);
INSERT INTO Books VALUES (9780103243,'New Perspectives on Microsoft (R) Project 2010 : Introductory','Personal Development',7);
INSERT INTO Books VALUES (9780103244,'Super-Easy Baby Blankets ','Personal Development',7);
INSERT INTO Books VALUES (9780103245,'Henri Samuel : Master of the French Interior','Personal Development',8);
INSERT INTO Books VALUES (9780103246,'How to Start a Home-based Makeup Artist Business','Personal Development',3);
INSERT INTO Books VALUES (9780103247,'History of Men''s Accessories: a Short Guide for Men About Town','Personal Development',9);
INSERT INTO Books VALUES (9780103248,'I Have No Secrets','Personal Development',9);
INSERT INTO Books VALUES (9780103249,'Beginning Drupal 8','Personal Development',6);
INSERT INTO Books VALUES (9780103250,'Programm Ejercicios - Aleman Para Hispanohablantes','Consumer Advice',0);
INSERT INTO Books VALUES (9780103251,'Interiors (Merlot Red Edition) : The Greatest Rooms of the Century','Popular Psychology',5);
INSERT INTO Books VALUES (9780103252,'Miss Manners'' Guide to a Surprisingly Dignified Wedding','Mind, Body, Spirit: Thought and Practice',1);
INSERT INTO Books VALUES (9780103253,'Bella Figura : How to Live, Love and Eat the Italian Way','Fortune-telling and Divination',5);
INSERT INTO Books VALUES (9780103254,'I am Rosa Parks','Complementary Therapies, Healing and Health',5);
INSERT INTO Books VALUES (9780103255,'Web Development Recipes 2e','Aromatherapy and Essential Oils',9);
INSERT INTO Books VALUES (9780103256,'The Spa Book : The Official Guide to Spa Therapy','General Cookery',2);
INSERT INTO Books VALUES (9780103257,'Sewing Edges and Corners : An Embellishment Idea Book','General Cookery',4);
INSERT INTO Books VALUES (9780103258,'Ze French Do it Better : A Lifestyle Guide','General Cookery',6);
INSERT INTO Books VALUES (9780103259,'Toilet Paper Crafts for Holidays and Special Occasions : 60 Papercraft, Sewing, Origami and Kanzashi Projects','General Cookery',3);
INSERT INTO Books VALUES (9780103260,'A MILLION ANGELS','General Cookery',9);
INSERT INTO Books VALUES (9780103261,'Fundamentals of Web Development, Global Edition','General Cookery',4);
INSERT INTO Books VALUES (9780103262,'The Wizard''s Dessert Cookbook ','Beverages',7);
INSERT INTO Books VALUES (9780103263,'Make Your Own Natural Soaps : All Vegetable Herbal Recipes','Antiques and Collectables',7);
INSERT INTO Books VALUES (9780103264,'This Is Home : Design for a Cozy Life','Fashion and Style Guides',3);
INSERT INTO Books VALUES (9780103265,'Pale and Interesting : Decorating with Whites, Pastels and Neutrals for a Warm and Welcoming Home','Fashion and Style Guides',4);
INSERT INTO Books VALUES (9780103266,'Magic Carpet Race! (Shimmer and Shine)','Fashion and Style Guides',4);
INSERT INTO Books VALUES (9780103267,'Programming Microsoft Dynamics NAV 2009','Cosmetics, Hair and Beauty',2);
INSERT INTO Books VALUES (9780103268,'Glamour : Women, History, Feminism','Cosmetics, Hair and Beauty',5);
INSERT INTO Books VALUES (9780103269,'Fun with Folded Fabric Boxes : All No-sew Projects, Fat-quarter Friendly, Elegance in Minutes','Cosmetics, Hair and Beauty',5);
INSERT INTO Books VALUES (9780103270,'Ancient Secrets of Facial Rejuvenation : A Non-surgical Approach to Youth and Well-being','Cosmetics, Hair and Beauty',7);
INSERT INTO Books VALUES (9780103271,'The Bearded Gentleman : The Style Guide to Shaving Face','Cosmetics, Hair and Beauty',3);
INSERT INTO Books VALUES (9780103272,'LGB I Love You, Daddy','Cosmetics, Hair and Beauty',9);
INSERT INTO Books VALUES (9780103273,'Learn to Produce Video with Ffmpeg : In Thirty Minutes or Less (2018 Edition)','Cosmetics, Hair and Beauty',0);
INSERT INTO Books VALUES (9780103274,'Supermodels'' Beauty Secrets : Hot tips for style, beauty and fashion from the world''s top models','Cosmetics, Hair and Beauty',3);
INSERT INTO Books VALUES (9780103275,'Origami Boxes','Cosmetics, Hair and Beauty',1);
INSERT INTO Books VALUES (9780103276,'True British : Alice Temperley','Interior Design, Decor and Style Guides',8);
INSERT INTO Books VALUES (9780103277,'The Vintage Sweet Book : A Complete Guide to Vintage Sweets and Cocktail Party Treats','Interior Design, Decor and Style Guides',2);
INSERT INTO Books VALUES (9780103278,'Horrid Henry''s Joke Book','Interior Design, Decor and Style Guides',7);
INSERT INTO Books VALUES (9780103279,'Photography Demystified : Your Guide to the World of Travel Photography','Interior Design, Decor and Style Guides',1);
INSERT INTO Books VALUES (9780103280,'Inspiring Tiny Homes : Creative Living on Land, on the Water, and on Wheels','Interior Design, Decor and Style Guides',8);
INSERT INTO Books VALUES (9780103281,'The Date Night Cookbook : Romantic Recipes and Easy Ideas to Inspire from Dawn Till Dusk','Interior Design, Decor and Style Guides',4);
INSERT INTO Books VALUES (9780103282,'Space Works : A Source Book of Design and Decorating Ideas to Create Your Perfect Home','Shopping Guides',3);
INSERT INTO Books VALUES (9780103283,'Living in Style: Best Interior Design on the Planet','Shopping Guides',5);
INSERT INTO Books VALUES (9780103284,'What on Earth Do You Do When Someone Dies?','Weddings, Wedding Planners',3);
INSERT INTO Books VALUES (9780103285,'Avid Media Composer 6.X Cookbook','Weddings, Wedding Planners',8);
INSERT INTO Books VALUES (9780103286,'The Clear Skin Cookbook : The vital vitamins and magic minerals you need for smooth, blemish-free, younger-looking skin','Parties, Etiquette and Entertaining',1);
INSERT INTO Books VALUES (9780103287,'Anatomia del Hatha Yoga','Crafts and Hobbies',5);
INSERT INTO Books VALUES (9780103288,'La Combinacion de Los Alimentos','Crafts and Hobbies',3);
INSERT INTO Books VALUES (9780103289,'Furniture and Interiors of the 1970s','Crafts and Hobbies',4);
INSERT INTO Books VALUES (9780103290,'Of Mice and Aliens : An Asperger Adventure','Crafts and Hobbies',2);
INSERT INTO Books VALUES (9780103291,'Introduction to Finite Element Analysis Using SolidWorks Simulation 2014','Crafts and Hobbies',8);
INSERT INTO Books VALUES (9780103292,'Home Decoration in Crochet : 25 Colorful Designs to Brighten Your Home','Crafts and Hobbies',9);
INSERT INTO Books VALUES (9780103293,'When Love Speaks : Poetry and prose for weddings, relationships and married life.','Crafts and Hobbies',5);
INSERT INTO Books VALUES (9780103294,'Real Nordic Living : Design. Food. Art. Travel.','Crafts and Hobbies',1);
INSERT INTO Books VALUES (9780103295,'Embroidery pour le Jardinier : 100 French Designs for the Gardener','Crafts and Hobbies',2);
INSERT INTO Books VALUES (9780103296,'Jemima Small Versus the Universe','Painting and Art Manuals',8);
INSERT INTO Books VALUES (9780103297,'Beginning Silverlight 5 in C#','Painting and Art Manuals',0);
INSERT INTO Books VALUES (9780103298,'Home of Your Own: Creating Interiors with Character','Needlework and Fabric Crafts',1);
INSERT INTO Books VALUES (9780103299,'New Dress A Day','Needlework and Fabric Crafts',7);
INSERT INTO Books VALUES (9780103300,'George Washington''s Rules of Civility and Decent Behavior','Needlework and Fabric Crafts',7);
INSERT INTO Books VALUES (9780103301,'Farrow and Ball Living with Colour','Needlework and Fabric Crafts',9);
INSERT INTO Books VALUES (9780103302,'The Pain and the Great One','Needlework and Fabric Crafts',6);
INSERT INTO Books VALUES (9780103303,'Instant AutoIt Scripting','Needlework and Fabric Crafts',8);
INSERT INTO Books VALUES (9780103304,'Houses That We Dreamt Of : The Interiors of Delphine and Reed Krakoff','Needlework and Fabric Crafts',8);
INSERT INTO Books VALUES (9780103305,'Feng Shui Home','Embroidery Crafts',7);
INSERT INTO Books VALUES (9780103306,'Home Sewn Home: 20 Projects to Make for the Retro Home','Quiltmaking, Patchwork and Applique',0);
INSERT INTO Books VALUES (9780103307,'The Dinner Party Diary','Quiltmaking, Patchwork and Applique',9);
INSERT INTO Books VALUES (9780103308,'Loved','Knitting and Crochet',7);
INSERT INTO Books VALUES (9780103309,'Implementing SAP SuccessFactors : A Client Centered Approach','Knitting and Crochet',1);
INSERT INTO Books VALUES (9780103310,'Making Cushions and Pillows : 60 cushions and pillows to sew, stitch, knit and crochet','Ropework, Knots and Macrame',5);
INSERT INTO Books VALUES (9780103311,'Bent, Bound and Stitched : Collage, Cards and Jewelry with a Twist','Jewellery and Beadcraft',3);
INSERT INTO Books VALUES (9780103312,'How to Iron Your Own Damn Shirt ','Jewellery and Beadcraft',1);
INSERT INTO Books VALUES (9780103313,'The Nature of Home : Creating Timeless Houses','Jewellery and Beadcraft',1);
INSERT INTO Books VALUES (9780103314,'Meditation Is an Open Sky : Mindfulness for Kids','Jewellery and Beadcraft',8);
INSERT INTO Books VALUES (9780103315,'Digital Identity and Social Media','Book and Paper Crafts',2);
INSERT INTO Books VALUES (9780103316,'Mindful London : How to Find Calm and Contentment in the Chaos of the City','Book and Paper Crafts',6);
INSERT INTO Books VALUES (9780103317,'Living with Less : How to Downsize to 100 Personal Possessions','Flower Arranging and Floral Crafts',3);
INSERT INTO Books VALUES (9780103318,'Do You Know Your Groom?','Funny Books and Stories',7);
INSERT INTO Books VALUES (9780103319,'New and Improved Bartender''s Manual : Or How to Mix Drinks of the Present Style','Funny Books and Stories',9);
INSERT INTO Books VALUES (9780103320,'Making Bombs for Hitler','Funny Books and Stories',8);
INSERT INTO Books VALUES (9780103321,'Getting Started with Flex 3 : An Adobe Developer Library Pocket Guide for Developers','Funny Books and Stories',0);
INSERT INTO Books VALUES (9780103322,'Stained Glass Mosaics : Original Projects for Beginners','Funny Books and Stories',1);
INSERT INTO Books VALUES (9780103323,'Homespun Style','Cartoons and Comic Strips',9);
INSERT INTO Books VALUES (9780103324,'Markham Roberts : Decorating the Way I See It','TV Tie-in Humour',9);
INSERT INTO Books VALUES (9780103325,'Rooms to Inspire in the City : Stylish Interiors for Urban Living','TV Tie-in Humour',6);
INSERT INTO Books VALUES (9780103326,'Attention, Girls! : A Guide to Learn All About Your AD/HD','TV Tie-in Humour',1);
INSERT INTO Books VALUES (9780103327,'Sergey''s Html5 and Css3 Quick Reference. Html5, Css3 and APIs (3rd Edition)','TV Tie-in Humour',2);
INSERT INTO Books VALUES (9780103328,'Fashion in the Time of William Shakespeare : 1564-1616','TV Tie-in Humour',1);
INSERT INTO Books VALUES (9780103329,'100 Beautiful Bracelets','TV Tie-in Humour',0);
INSERT INTO Books VALUES (9780103330,'Maths and English for Hairdressing : Functional Skills','TV Tie-in Humour',6);
INSERT INTO Books VALUES (9780103331,'Lithuania - Culture Smart! : The Essential Guide to Customs and Culture','TV Tie-in Humour',6);
INSERT INTO Books VALUES (9780103332,'Mr Greedy','TV Tie-in Humour',4);
INSERT INTO Books VALUES (9780103333,'Sams Teach Yourself Active Server Pages 3.0 in 21 Days','TV Tie-in Humour',2);
INSERT INTO Books VALUES (9780103334,'Thierry Mugler : Couturissime','TV Tie-in Humour',8);
INSERT INTO Books VALUES (9780103335,'Chair Caning and Seat Weaving: Storey''s Country Wisdom Bulletin A.16','Guidebooks',2);
INSERT INTO Books VALUES (9780103336,'Get Momentum','Guidebooks',10);
INSERT INTO Books VALUES (9780103337,'Maidens, Myths and Mermaids','Pentecostal Churches',5);
INSERT INTO Books VALUES (9780103338,'Puppy Mind','Personal Christian Testimony and Popular Inspirational Works',9);
INSERT INTO Books VALUES (9780103339,'Craft Notes for Animators : A Perspective on a 21st Century Career','Christian Institutions and Organizations',2);
INSERT INTO Books VALUES (9780103340,'The Inspirational Moustache','Buddhist Books',2);
INSERT INTO Books VALUES (9780103341,'Awesome Duct Tape Projects','Judaism: Worship, Rites and Ceremonies',9);
INSERT INTO Books VALUES (9780103342,'How to Restore Old Furniture Guide','Celtic Religion and Mythology',3);
INSERT INTO Books VALUES (9780103343,'Peranakan Chinese Home : Art and Culture in Daily Life','Worship, Rites and Ceremonies',9);
INSERT INTO Books VALUES (9780103344,'Scholastic Reader Level 1: Noodles: I Love School : I Love School!','Language: Reference and General',3);